name: Build Windows Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Windows Executable
      run: npm run package-win

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NetPulseStudio-Windows
        path: dist/NetPulseStudio-win32-x64/
